### ISSUE TITLE
Does it support wss (SSL)?

### ISSUE THREAD

**Issue by cangooroo88** [immusen/yii2-swoole-websocket#9]
Sorry, couldn't find it anywhere else, does this package supports usage of SSL and do I have to setup it?

**Comment by immusen** [comment]
You can try to add SSL parameters into server section of config file, Such as ssl_cert_file, ssl_key_file, ssl_method..  
Config example: yii2-swoole-websocket/example/websocket/config/params.php

Docs: https://wiki.swoole.com/#/server/setting?id=ssl_cert_file

More easy way to get SSL support for your project is use Nginx proxy. You can add SSL support with Nginx and make it support websocket proxy
